---

# Check if the container is running.  If it is, dont' run it
- name: Check if {{ containers.grafana.name }} is running
  include: roles/ansible_docker_utils/tasks/is_container_running.yml
  vars:
    docker_name: "{{ containers.grafana.name }}"

# Pull the image from ECR
- name: Pull {{ containers.grafana.name }} from ECR
  include: roles/ansible_aws/tasks/ansible_aws_pull_from_ecr.yml
  vars:
    ansible_aws_image_name: "{{ containers.grafana.name }}"
    ansible_aws_image_tag: "{{ containers.grafana.version }}"
  when: ansible_aws_pull_from_ecr is defined


# Run the container if it isn't running
- name: Launch the container {{ containers.grafana.name }}
  include: roles/ansible_docker_utils/tasks/run_container.yml
  vars:
    docker_name: "{{ containers.grafana.name }}"
    docker_domain_name: "{{ weave.domain_name }}"
    docker_volume_args: "{{ containers.grafana.volume_args }}"
    docker_extra_args: "-d
                        --restart=always
                        -p {{ containers.grafana.port }}:{{ containers.grafana.port }}
                        {{ common_logging_params }}
                        {{ weave_docker_args }}"
  register: result
  when: "not {{docker_container_is_running }}"
