---

- name: Teardown DB volumes if necessary
  include: teardown_volume.yml
  when: teardown_db_volumes is defined
  tags:
    - teardown_volumes
    - teardown_db_volumes

- name: Teardown the DB containers if necessary
  include: teardown_containers.yml
  when: teardown_db_containers is defined
  tags:
    - teardown_containers
    - teardown_db_containers

- name: Build the DB volumes
  include: build_volumes.yml
  when: build_volumes is defined
  tags:
    - db
    - build
    - build_volumes
    - build_db_volumes


- name: Build the DB containers
  include: build_containers.yml
  when: build_containers is defined
  tags:
    - db
    - build
    - build_db

- name: Run the DB containers
  include: run_containers.yml
  when: run_containers is defined
  tags:
    - db
    - run
    - run_db





