---

- name: Populate and copy the grafana_prometheus config
  template:
    src: prometheus.yml.j2
    dest: "{{ grafana.base_dir }}/prometheus/prometheus.yml"

- name: Build the grafana_prometheus container
  include: roles/ansible_docker_utils/tasks/build_container.yml
  vars:
    docker_name: "{{ containers.grafana_prometheus.name }}"
    docker_dockerfile: "{{ grafana.dockerfiles_path }}/{{ containers.grafana_prometheus.dockerfile }}"
    docker_build_args: "{{ grafana.build_args }}"
    docker_base_dir: "{{ grafana.base_dir }}"

#- debug: var=docker_result.stdout_lines

