---

# These are the volumes used by grafana_prometheus to store its data
# TODO These will end up being ECS thingies
# ES Volume

- name: Create grafana data volume
  include: roles/ansible_docker_utils/tasks/create_volume.yml
  vars:
    docker_name: "{{ volumes.grafana_prometheus.name }}"
  register: result
