#!/usr/bin/env /usr/bin/ansible-playbook
---

- hosts: localhost
  vars_files:
    - "{{ grafana_config_file }}"
  roles:
    - common
    - ansible_docker_utils
    - ansible_weave

    # Get AWS secrets
    - role: ansible_secrets
      ansible_secrets_get_secrets_from_s3: true
      ansible_secrets_list: "{{ aws_secrets_list }}"

    # Get Grafana secrets
    - role: ansible_secrets
      ansible_secrets_get_secrets_from_s3: true
      ansible_secrets_list: "{{ grafana_secrets_list }}"