#!/usr/bin/env /usr/bin/ansible-playbook
---

- hosts: localhost
  vars_files:
    - "{{ grafana_config_file }}"
  roles:
    - common
    - ansible_docker_utils
    - ansible_weave
    - teardown



